#!/bin/bash

echo "🎥 Video URL Setup Helper"
echo "========================="
echo ""
echo "After uploading your video to GitHub Releases, your URL will be:"
echo ""
echo "https://github.com/keanlouis30/EaselyBot/releases/download/v1.0.0-video/canvas_tutorial.mp4"
echo ""
echo "Steps to complete setup:"
echo ""
echo "1. Copy the URL above"
echo ""
echo "2. Go to Render Dashboard:"
echo "   https://dashboard.render.com/"
echo ""
echo "3. Click on your 'easelybot' service"
echo ""
echo "4. Go to 'Environment' tab"
echo ""
echo "5. Add new environment variable:"
echo "   Key: VIDEO_TUTORIAL_URL"
echo "   Value: [paste the URL]"
echo ""
echo "6. Click 'Save Changes'"
echo ""
echo "7. Render will automatically redeploy with video support!"
echo ""
echo "==============================================="
echo "Alternative: Test the URL locally first:"
echo ""
echo "export VIDEO_TUTORIAL_URL=\"https://github.com/keanlouis30/EaselyBot/releases/download/v1.0.0-video/canvas_tutorial.mp4\""
echo ""
echo "Then run your bot locally to test if the video card appears."