#!/bin/bash

# Script to upload video to GitHub Release
# This will make the video publicly accessible via URL

echo "📺 Uploading Canvas Tutorial Video to GitHub Release..."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://github.com/keanlouis30/EaselyBot/releases/new"
echo ""
echo "2. Fill in the release details:"
echo "   - Tag version: v1.0.0-video"
echo "   - Release title: Canvas Tutorial Video"
echo "   - Description: Video tutorial for generating Canvas access tokens"
echo ""
echo "3. Drag and drop the file 'canvas_tutorial.mp4' to the attachment area"
echo ""
echo "4. Click 'Publish release'"
echo ""
echo "5. After publishing, right-click on 'canvas_tutorial.mp4' and copy link address"
echo ""
echo "6. The URL will look like:"
echo "   https://github.com/keanlouis30/EaselyBot/releases/download/v1.0.0-video/canvas_tutorial.mp4"
echo ""
echo "7. Go to Render Dashboard → Environment → Add variable:"
echo "   VIDEO_TUTORIAL_URL=[paste the URL here]"
echo ""
echo "The video file is located at: $(pwd)/canvas_tutorial.mp4"
echo "Size: $(ls -lh canvas_tutorial.mp4 | awk '{print $5}')"